# This is where all of your database configs are
database:
  # This is the type of data querying language you want.
  # The choices are "MySQL", "MariaDB", and "MongoDB"
  type: "MySQL"

  # The address of your hosted database. Example: "localhost:3306"
  address: "localhost:27017"

  # Username and Password refer to the auth username and auth password for the database
  username: "username"
  password: "password"

  # This is the name of the database
  collection: "Ecoverse"

  # This is the custom URI (Mostly here for mongodb users) ## OPTIONAL
  # URI: ""

  # What is the maximum pool-size (Pretty self explanitory)
  max-pool-size: 10

  # If you want SSL enabled or disabled
  ssl: false

# This is where you default configs are
default:
  balance: 100.0
  ticker: "$"

# This is your scoreboard
scoreboard:
  enabled: true
  hidden-by-default: false

  title: "<#FFFFFF>&l- Wall-Y.ca -</#FFFF00>"
  lines:
    - ""
    - "&4&l ^z^t&r Kills: &4%statistic_player_kills%"
    - "&6&l ^=^r^`&r Deaths: &6%statistic_deaths%"
    - "&a&l$&r Money: &a%vault_eco_balance_formatted%"
    - "&e&l ^o &r Playtime: &e%ptr_playtime_days%d %ptr_playtime_hours_trimmed%h"
    - "&9&l ^=^q &r Rank: %luckperms_suffix%"