# This is where all of your database configs are
database:
  # This is the type of data querying language you want.
  # The choices are "MySQL", "MariaDB", and "MongoDB"
  type: "MySQL"

  # Host is the ip of your hosted DB and port is the hosted port
  host: "localhost"
  port: 3306

  # Username and Password refer to the auth username and auth password for the database
  username: "username"
  password: "password"

  # This is the name of the database
  collection: "Ecoverse"

# This is where you default configs are
default:
  balance: 100.0
  ticker: "$"

# This is your scoreboard
scoreboard:
  enabled: true
  hidden-by-default: false

  title: "<#FFFFFF>&l- Wall-Y.ca -</#FFFF00>"
  lines:
    - ""
    - "&4&l ^z^t&r Kills: &4%statistic_player_kills%"
    - "&6&l ^=^r^`&r Deaths: &6%statistic_deaths%"
    - "&a&l$&r Money: &a%vault_eco_balance_formatted%"
    - "&e&l ^o &r Playtime: &e%ptr_playtime_days%d %ptr_playtime_hours_trimmed%h"
    - "&9&l ^=^q &r Rank: %luckperms_suffix%"